## Generate wallpapers
#
#name: Go

on:
    workflow_dispatch:
    schedule:
        - cron: 0 6 * * *

jobs:

  build:
    name: Create Wallpaper
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Make wallpaper
      run: ./pixel3.sh

# Add other images/types here
    - name: Commit new image
      run: |
        git status
        ls -l
        pwd
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pixel3.png
        git add lines_old
        git commit -m "Generated new wallpapers"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: trunk
